### ISSUE TITLE
textColor property transparency issue on Safari Mac

### ISSUE THREAD

**Issue by ynuska** [haldarmahesh/reactjs-mapple-tooltip#10] opened 2016-11-22 08:58 UTC
Hi,
Thx for making this component very easy to use  👍 
There is an issue with the textColor property. on Safari Mac. The font color has some transparency. Is there any chance to fix this issue soon ?
Thx in advance,
Ina K

**Comment by haldarmahesh** [comment] 2016-12-11 13:06
Hey @ynuska,
Thanks for appreciating the effort 🙂 

For the issue you were referring I tried to replicate it on safari, I could not see any transparency issue. I used `textColor: 'red'`
Please check the screenshot.
<img width="619" alt="screen shot 2016-12-11 at 18 33 47" src="https://cloud.githubusercontent.com/assets/7925734/21080249/8aac3214-bfd0-11e6-875b-d6f99f9925ea.png">

Can you please share the screenshot so that I can find where the issue is?

Thanks 🙂

**Comment by ynuska** [comment] 2016-12-12 08:13
Thank you for your question. I will come back with a prinscreen. I'm not using a MAC, but one of my colleagues does. I will ask for a printscreen. In the meantime, I will give you few details that I hope will help you to reproduce the issue.
 
I’m using this version"reactjs-mappletooltip": "^1.4.63",
 
This is the way I’m using it:
 
< div className={styles.tooltipContainer} >
    < MappleToolTip direction={'bottom'}
                   textColor='#FFF'
                   backgroundColor='#000000'
                   fadeInAnimation={false}>
    < span > … </ span >
    < /MappleToolTip >
< /div >
 
The container has this style
 
.tooltipContainer {
    display: inline-table;
}
 

Thank you,
ynuska

**Comment by ynuska** [comment] 2016-12-12 08:57
expectedresult

 ![expectedresult](https://cloud.githubusercontent.com/assets/3414989/21133987/e012d89c-c11b-11e6-8b1e-146678c1b896.png)

currentresult:

![currentresult](https://cloud.githubusercontent.com/assets/3414989/21093284/3bd4538e-c051-11e6-910e-0adda3091ec0.png)

The color works perfectly on other browsers.

Thx in advance,
ynuska

**Comment by haldarmahesh** [comment] 2016-12-13 06:41
@ynuska 
Hey, which color you applied on the tooltip?
And where is the transparency? I think I did not get the issue by seeing the screenshots.

Can you please elaborate more?

**Comment by ynuska** [comment] 2016-12-13 08:56
sorry, the code snippet wasn't visible because of the html tags :) . I put some space in between now so you can see it. thank you in advance.

**Comment by haldarmahesh** [comment] 2016-12-13 15:56
Hey @ynuska,
Thanks for the code. 
In the screenshot you provided, I see no transparency in fonts.
I am not getting the issue.

It would help this toolTip to grow if you can exactly guide me how to replicate this issue.

Thanks

**Comment by ynuska** [comment] 2016-12-15 12:54
Hi,
if you compare the first printscreen (expected result) with the second (current result) you will notice that the color font (white) has a different intensity. This is the issue I was talking about .. I know it's not a big issue, my designer asked me if I can fix it and that's why I took this action. thx in advance,

**Comment by haldarmahesh** [comment] 2017-01-17 07:25
@ynuska Hey I really could not replicate this issue, for now I am closing this issue. If you still face some issues and can provide the code snippets, that will really help and re open the issue.

thanks @ynuska

**Closed as completed by haldarmahesh** 2017-01-17 07:25 UTC
